In [ ]:
import pandas as pd
from dateutil import parser

# Load the CSV file
data = pd.read_csv('/content/drive/MyDrive/Thesis datasets/sales_data_sample - Copy.csv', encoding='latin1')

# column with dates is named 'date_column'
date_column = data['Order Date']

# Check some first few rows
print(date_column.head())

# Try to parse the first date to infer the format
sample_date = date_column.iloc[1]
print(f"Sample Date: {sample_date}")

try:
    # Automatically infer the format using dateutil
    parsed_date = parser.parse(sample_date)
    print(f"Parsed Date: {parsed_date}")
except Exception as e:
    print(f"Error parsing date: {e}")

0     2/24/2003
1    2003-02-24
2      5/7/2003
3      7/1/2003
4     8/25/2003
Name: Order Date, dtype: object
Sample Date: 2003-02-24
Parsed Date: 2003-02-24 00:00:00

In [ ]:
import pandas as pd
from datetime import datetime

# Define date formats
date_formats = [
   "%Y-%m-%d",    # 2023-01-07
   # "%d-%m-%Y",    # 07-01-2023
   "%m/%d/%Y",    # 01/07/2023
    #"%d/%m/%Y",    # 07/01/2023
   # "%b %d, %Y",   # Jan 07, 2023
   # "%d %b %Y",    # 07 Jan 2023
]

# Read the CSV file
data = pd.read_csv('/content/drive/MyDrive/Thesis datasets/sales_data_sample - Copy.csv', encoding='latin1')

# Assuming the column with dates is named 'date_column'
date_column = data['Order Date']

# Function to identify the format of a date
def identify_date_format(date_str):
    for fmt in date_formats:
        try:
            datetime.strptime(date_str, fmt)
            return fmt  # Return the matching format
        except ValueError:
            continue
    return None  # Return None if no format matches

# Apply the function to the date column
data['detected_format'] = date_column.apply(identify_date_format)


# Loop through each detected date format
for fmt in date_formats:
    # Filter rows by the specific date format
    filtered_rows = data[data['detected_format'] == fmt]

    # Print the rows with the specific format
    print(f"Rows with format {fmt}:")

    # Specify the field/column to display (e.g., 'date_column')
    specific_field = filtered_rows[['Order No','Order Date']]  # Replace 'date_column' with your column name

    # Print the specific field
    print(specific_field)

# Find rows with unrecognized formats
# unrecognized_dates = data[data['detected_format'].isna()]
# print("Rows with unrecognized date formats:")
# print(unrecognized_dates)

Rows with format %Y-%m-%d:
   Order No  Order Date
1     10107  2003-02-24
Rows with format %m/%d/%Y:
      Order No  Order Date
0        10107   2/24/2003
2        10121    5/7/2003
3        10134    7/1/2003
4        10145   8/25/2003
5        10159  10/10/2003
...        ...         ...
2821     10350   12/2/2004
2822     10373   1/31/2005
2823     10386    3/1/2005
2824     10397   3/28/2005
2825     10414    5/6/2005

[2825 rows x 2 columns]

In [ ]:
import pandas as pd
from datetime import datetime

# Define common date formats
date_formats = [
   "%Y-%m-%d",    # 2023-01-07
   # "%d-%m-%Y",    # 07-01-2023
   "%m/%d/%Y",    # 01/07/2023
    #"%d/%m/%Y",    # 07/01/2023
   # "%b %d, %Y",   # Jan 07, 2023
   # "%d %b %Y",    # 07 Jan 2023
]

# Read the CSV file
data = pd.read_csv('/content/drive/MyDrive/Thesis datasets/sales_data_sample - Copy.csv', encoding='latin1')

# Assuming the column with dates is named 'date_column'
date_column = data['Order Date']

# Function to identify the format of a date
def identify_date_format(date_str):
    for fmt in date_formats:
        try:
            datetime.strptime(date_str, fmt)
            return fmt  # Return the matching format
        except ValueError:
            continue
    return None  # Return None if no format matches

# Apply the function to the date column
data['detected_format'] = date_column.apply(identify_date_format)


# Loop through each detected date format
for fmt in date_formats:
    # Filter rows by the specific date format
    filtered_rows = data[data['detected_format'] == fmt]

    # Check if there are any rows with the current format
    if not filtered_rows.empty:
        # Get one sample (e.g., the first row)
        sample_row = filtered_rows[['Order No', 'Order Date']].iloc[0]

        # Print the format and the sample
        print(f"Sample for format {fmt}:")
        print(sample_row)
    else:
        # Print if no rows match the format
        print(f"No rows found with format {fmt}.")

Sample for format %Y-%m-%d:
Order No           10107
Order Date    2003-02-24
Name: 1, dtype: object
Sample for format %m/%d/%Y:
Order No          10107
Order Date    2/24/2003
Name: 0, dtype: object

In [ ]:
import pandas as pd

# Step 1: Load the CSV file
data = pd.read_csv('/content/drive/MyDrive/Thesis datasets/sales_data_sample - Copy.csv', encoding='latin1')

# Step 2: Convert 'Order Date' to datetime, let pandas infer the format
data['Order Date'] = pd.to_datetime(data['Order Date'], errors='coerce')

# Step 3: Reformat the 'Order Date' to '%Y-%m-%d' format
# This step converts the datetime to a string in the desired format
data['Date'] = data['Order Date'].dt.strftime('%Y-%m-%d')

# Step 4: Save the updated date format to a new CSV file
data.to_csv('updated_file.csv', index=False)

# Print the updated data with new date format
print(data[['Order No', 'Order Date']])

      Order No Order Date
0        10107 2003-02-24
1        10107 2003-02-24
2        10121 2003-05-07
3        10134 2003-07-01
4        10145 2003-08-25
...        ...        ...
2821     10350 2004-12-02
2822     10373 2005-01-31
2823     10386 2005-03-01
2824     10397 2005-03-28
2825     10414 2005-05-06

[2826 rows x 2 columns]

In [ ]:
import pandas as pd

# Step 1: Load the CSV file
data = pd.read_csv('/content/drive/MyDrive/Thesis Notebooks/output_Problem 3_Lack of Standard Data Models (1).csv', encoding='latin1')

# Step 2: Convert 'Order Date' to datetime, let pandas infer the format
data['Order Date'] = pd.to_datetime(data['Order Date'], errors='coerce')

# Step 3: Reformat 'Order Date' to '%Y-%m-%d' only if it's not already in that format
# We will use a helper function to check the format
def reformat_date(date):
    if pd.isna(date):
        return date
    # Check if the date is already in '%Y-%m-%d' format
    if date.strftime('%Y/%d/%m') == date:
        return date
    return date.strftime('%Y/%d/%m')

# Apply the reformat_date function to the 'Order Date' column
data['Order Date'] = data['Order Date'].apply(reformat_date)

# Change 'Order Date' format into a new 'Order Date New' column
data['Order Date New'] = data['Order Date']

# Step 4: Save the updated DataFrame to a new CSV file
data.to_csv('updated_file.csv', index=False)

# Print the updated new data format
print(data[['Order No', 'Order Date New']])

      Order No Order Date New
0        10107     2003/24/02
1        10121     2003/07/05
2        10134     2003/01/07
3        10145     2003/25/08
4        10159     2003/10/10
...        ...            ...
2818     10350     2004/02/12
2819     10373     2005/31/01
2820     10386     2005/01/03
2821     10397     2005/28/03
2822     10414     2005/06/05

[2823 rows x 2 columns]

In [ ]:
import pandas as pd

# Step 1: Load the CSV file
data = pd.read_json('/content/drive/MyDrive/Thesis Notebooks/modern_data (2).json', encoding='latin1')

# Step 2: Convert 'Order Date' to datetime, letting pandas infer the format
data['Order Date'] = pd.to_datetime(data['Order Date'], errors='coerce')

# Step 3: Reformat 'Order Date' to '%Y-%m-%d'
data['Order Date'] = data['Order Date'].dt.strftime('%Y-%m-%d')

# Step 4: Save the updated DataFrame to a new JSON file
data.to_json('updated_file.json', orient='records', date_format='iso', indent=4)

print("JSON file updated and saved successfully.")

JSON file updated and saved successfully.